cmake_minimum_required(VERSION 4.1)
project(CCC)

set(CMAKE_CXX_STANDARD 20)

add_executable(ccc_2018_j2 "CCC/2018/CCC '18 J2 - Occupy parking .cpp")
add_executable(ccc_2022_j2 "CCC/2022/CCC '22 J2 - Fergusonball Ratings.cpp")
add_executable(ccc_2023_j1 "CCC/2023/CCC '23 J1 - Deliv-e-droid.cpp")
add_executable(ccc_2021_j3 "CCC/2021/CCC '21 J3 - Secret Instructions.cpp")
add_executable(ccc_2016_j2 "CCC/2016/CCC '16 J2 - Magic Squares.cpp")
add_executable(ccc_2020_s1 "CCC/2020/CCC '20 S1 - Surmising a Sprinter's Speed.cpp")
add_executable(ccc_2026_s2 "CCC/2026/CCC '26 S2 - Beams of Light V1.cpp")
add_executable(ccc_2026_s2V1 "CCC/2026/CCC '26 S2 - Beams of Light V2.cpp")
add_executable(ccc_2025_j3 "CCC/2025/CCC '25 J3 - Product Codes .cpp")
add_executable(ccc_2009_j4 "CCC/2009/CCC '09 J4 - Signage.cpp")
add_executable(rockClimbing "Others/Rock Climbing .cpp")
add_executable(ccc_2006_j2 "CCC/2006/CCC '06 J2 - Roll the Dice .cpp")
add_executable(ccc_2005_j3 "CCC/2005/CCC '05 J3 - Returning Home .cpp")
add_executable(ccc_2011_s2 "CCC/2011/CCC '11 S2 - Multiple Choice.cpp")
add_executable(ccc_96_s1 "CCC/Others/CCC '96 S1 - Deficient, Perfect, and Abundant.cpp")
add_executable(ccc_2001_s2 "CCC/2001/CCC '01 S2 - Spirals .cpp")
add_executable(ccc_2025_s2 "CCC/2025/CCC '25 S2 - Cryptogram Cracking Club.cpp")
add_executable(ccc_2025_j1 "CCC/2025/CCC '25 J1 - Roller Coaster Ride.cpp")
add_executable(codeforce1 "Others/A. P=NP.cpp")
add_executable(ccc_2004_j3 "CCC/2004/CCC '04 J3 - Smile with Similes.cpp")
add_executable(knapsackone "Others/Educational DP Contest AtCoder D - Knapsack 1.cpp")
add_executable(ccc_2002_j1 "CCC/2002/ CCC '02 J1 - 0123456789 (Hard).cpp")
add_executable(ccc_2000_j2 "CCC/2000/CCC '00 J2 - 9966.cpp")
add_executable(new_target7 "CCC/2000/CCC '00 S1 - Slot Machines .cpp")
add_executable(new_target "CCC/2021/CCC '21 J1 - Boiling Water .cpp")
add_executable(new_target1 "CCC/2000/CCC '00 S1 - Slot Machines .cpp")
add_executable(new_target2 "CCC/2024/CCC '24 J1 - Conveyor Belt Sushi .cpp")
add_executable(new_target3 "CCC/2004/CCC '04 S1 - Fix.cpp")
add_executable(new_target4 "Others/Mirrored Pairs.cpp")
add_executable(new_target5 "CCC/2014/CCC '14 J3 - Double Dice.cpp")
add_executable(new_target6 "CCC/2013/CCC '13 J4 - Time on task.cpp")
add_executable(new_target8 "CCC/Others/Olympic Scoring .cpp")
add_executable(new_target9 "CCC/2021/CCC '21 J2 - Silent Auction.cpp")
add_executable(new_target10 "CCC/2026/CCC '26 S1 - Baby Hop, Giant Hop.cpp")
add_executable(new_target11 "CCC/2017/CCC '17 S1 - Sum Game.cpp")
add_executable(new_target12 "CCC/2002/CCC '02 J2 - AmeriCanadian.cpp")
add_executable(new_target13 "CCC/2023/CCC '23 S2 - Symmetric Mountains.cpp")
add_executable(new_target14 "CCC/2019/CCC '19 S1 - Flipper.cpp")
add_executable(new_target15 "CCC/2019/CCC '19 S2 - Pretty Average Primes.cpp")
add_executable(new_target16 "Others/Amplitude Hackathon '23 Practice Problem 2 - Go Amplitude! .cpp")
add_executable(new_target17 "CCC/2007/CCC '07 J1 - Who is in the Middle.cpp")
add_executable(new_target18 "CCC/2008/CCC '08 J2 - Do the Shuffle.cpp")
add_executable(new_target19 "CCC/2006/CCC '06 J1 - Canadian Calorie Counting.cpp")
add_executable(new_target20 "CCC/2018/CCC '18 J3 - Are we there yet.cpp")
add_executable(new_target21 "CCC/2006/CCC '06 S1 - Maternity .cpp")
add_executable(new_target22 "CCC/2003/CCC '03 J1 - Trident .cpp")
add_executable(new_target23 "CCC/2000/CCC '00 S2 - Babbling Brooks .cpp")
add_executable(new_target24 "CCC/2025/CCC '25 S1 - Positioning Peter's Paintings.cpp")
add_executable(new_target25 "Others/Teamscode a).cpp")
add_executable(new_target26 "Others/Teamscode b).cpp")
add_executable(new_target27 "Others/Teamscode c).cpp")
add_executable(new_target28 "Others/Teamscode f).cpp")
add_executable(new_target29 "CCC/2017/CCC '17 S2 - High Tide, Low Tide.cpp")
add_executable(new_target30 "CCC/2005/CCC '05 J4 - Cross Spiral.cpp")
add_executable(new_target31 "COCI/2013/COCI '13 Contest 3 #1 Riječi .cpp")
add_executable(new_target32 "CCC/2018/CCC '18 S1 - Voronoi Villages .cpp")
add_executable(new_target33 "CCC/2002/CCC '02 S2 - Fraction Action.cpp")
add_executable(new_target34 "CCC/2003/ CCC '03 S1 - Snakes and Ladders .cpp")
add_executable(new_target35 "CCC/2019/CCC '19 J2 - Time to Decompress.cpp")
add_executable(new_target36 "Others/GFSS Christmas Challenge P4 - Coal Counting .cpp")
add_executable(new_target37 "CCC/2010/CCC '10 J1 - What is n, Daddy.cpp")
add_executable(new_target38 "Others/2657. Find the Prefix Common Array of Two Arrays.cpp")
add_executable(new_target39 "CCC/2025/CCC '25 J2 - Donut Shop .cpp")
add_executable(new_target40 "CCC/2017/CCC '17 J2 - Shifty Sum.cpp")
add_executable(new_target41 "CCC/2012/CCC '12 S1 - Don't pass me the ball!.cpp")
add_executable(new_target42 "Others/Arduino Circuit .cpp")
add_executable(new_target43 Others/Threes.cpp)
add_executable(new_target44 "CCC/2024/CCC '24 S1 - Hat Circle.cpp")
add_executable(new_target45 Hashmap.cpp)
add_executable(new_target46 "CCC/2007/CCC '07 J2 - I Speak TXTMSG .cpp")
add_executable(new_target47 "CCC/2012/CCC '12 J4 - Big Bang Secrets.cpp")
